### ISSUE TITLE
How to do post form stuff, for example upload pdf file?

### ISSUE THREAD

**Issue by albertwoo** [ronaldschlenker/FsHttp#19]

**Comment by ronaldschlenker** [comment]
For the next release, the binary and base64 as well as concenience functions for file upload (+multipart) will be included.

**Comment by albertwoo** [comment]
Thanks! Very looking forward for that!!!

Currently I made an ugly one for the workaround for my project:
```fsharp
type HttpBuilder with
    [<CustomOperation("MutipartFile")>]
    /// bytes: byte[] -> boundary: string -> dispositionType: string -> name: string -> filename: string -> contentType: string
    member this.MutipartFile(context: BodyContext, bytes, boundary, dispositionType, name, filename, contentType) =
        let byteArrayContent = new ByteArrayContent(bytes)
        byteArrayContent.Headers.ContentDisposition <- new ContentDispositionHeaderValue(dispositionType, Name = name, FileName = filename)
        byteArrayContent.Headers.ContentType        <- new MediaTypeHeaderValue(contentType)
        let content = new MultipartFormDataContent(boundary)
        content.Add(byteArrayContent, filename)
        
        { context with
            content = { content = ""; contentType = "application/text"; headers = [] }
            config =
                { context.config with
                    httpMessageTransformer =
                        Some (fun x ->
                                x.Content <- content
                                x) } }
```
So i can use it like below:
```fsharp
httpAsync {
    POST (sprintf "%s?eventid=%d" endPoint mktEventId)
    BearerAuth token
    body
    MutipartFile pdf ("-------" + DateTime.Now.Ticks.ToString("x")) "form-data" (filename.Split(".").First()) filename "application/pdf"
}
```

**Comment by lfr** [comment]
I'm also in need for MultiPartFile, I thought I could use BinaryUpload but since this ticket is still open I guess not... 😕

**Comment by ronaldschlenker** [comment]
ok, I think I'll have something working by end of this week...

**Comment by ronaldschlenker** [comment]
I just released a preview on nuget (2.0.0-preview1). @lfr @albertwoo @TheAngryByrd if anyone can give me feedback, it would be great.

You can see a usage example here:

https://github.com/ronaldschlenker/FsHttp/blob/0827e755ed21b3cfe8deb6990307e18e6d763d38/src/Tests/IntegrationTests.fs#L171

**Comment by ronaldschlenker** [comment]
I still have to print the FSI output for multipart, which is ignored at the moment.

**Comment by ronaldschlenker** [comment]
Better wait until I release a second preview this evening.

**Comment by ronaldschlenker** [comment]
ok, use 2.0.0-preview2 please...

**Comment by ronaldschlenker** [comment]
You mean like here:

https://github.com/ronaldschlenker/FsHttp/blob/5a999fc9321f505a704c4472a427d6f11c008a8f/src/Tests/IntegrationTests.fs#L253-L266

This example currently only works for single part body, but since one can specify a Content-Part for each part of a multi part element, I could add that?

I can make addPart public, too to have more control.

**Comment by ronaldschlenker** [comment]
Ok, I got it here:

https://github.com/ronaldschlenker/FsHttp/blob/7b60cb91aa72533ab98bb3df2ce16f4d6e2205bd/src/Tests/IntegrationTests.fs#L268-L294

Current version is 2.0.0: https://www.nuget.org/packages/SchlenkR.FsHttp/2.0.0
