### ISSUE TITLE
Additional steps needed for dotnet fsi usage

### ISSUE THREAD

**Issue by mtnrbq** [ronaldschlenker/FsHttp#20]
Following the instructions in [
Setup (F# Interactive)](https://github.com/ronaldschlenker/FsHttp#setup-f-interactive) section, but using dotnet fsi (.net core 3.0 preview 5), I get an error when executing a get - specifically `ERROR reading response content: System.IO.FileNotFoundException: Could not load file or assembly 'FSharp.Data, Version=3.0.0.0`

I needed to do the following to get it working:
`> open FSharp.Data;;`
`> printfn "load module %A" JsonSaveOptions.None;;`

After these 2 steps, the `get "https://reqres.in/api/users?page=2&delay=3" .> go;;` worked without error.

Not sure if you want this added to the instructions, or to wait and see if .net core 3.0 RTM rectifies the issue.

**Comment by ronaldschlenker** [comment]
relates to #22 and might be fixed (gotta test it in dotnet fsi)

**Comment by ronaldschlenker** [comment]
@mtnrbq can you check if this still occurs?

**Comment by mtnrbq** [comment]
This has been resolved.

From an easy FSI usability perspective, with F#5 and #r "nuget: ..." coming, would it be feasible to put the 'pretty printers' into the base package in another namespace ?

i.e. I would be able to do (once f#5.0 is released)
```
dotnet fsi

#r "nuget: SchlenkR.FsHttp";;
open FsHttp;;
open FsHttp.Dsl;;
open FsHttp.Fsi;;    <- name space for the pretty printers etc
fsipretty <- load up the pretty printers
get "https://reqres.in/api/users?page=2&delay=3" .> go;;
```

Anyways, just a thought, happy to do a test PR if you think it'd be worthwhile / appropriate

**Comment by ronaldschlenker** [comment]
Maybe instead of the `FsHttp.fsx` file, we could use `FSharp.Compiler.Interactive.Settings.fsi` object to register printer automatically once the assembly is loaded.
