### ISSUE TITLE
Retries with async

### ISSUE THREAD

**Issue by naartjie** [ronaldschlenker/FsHttp#58]
Thank you for this nice library, with great ergonomics.

I've been playing around with retrying http requests. I found [this snippet](http://www.fssnip.net/hr/title/Async-function-that-retries-work) for retrying any async "work". I soon realised that the `httpAsync { ... }` async builder fires off the request as soon as it's evaluated, i.e. it's a "hot" task like in C# land, rather than the cold async task idiomatic to F#, so I had to do some additional wrapping, and this is what I eventually came up with FsHttp:

```f#
let request =
    async { return! httpAsync { GET "http://httpbin.org/status/500:4,200:1" } }

let! result = retry request (fun r -> int r.statusCode = 200) 10
```

My question is: am I using this library correctly or am I missing a way to solve this more gracefully? Below is the full runnable example, with a modified retry function which makes the code slightly better (albeit the retry is specialised for http and doesn't work for any async task anymore):

<details>
<summary>Example.fsx</summary>
<p>

```f#
#r "nuget: SchlenkR.FsHttp, 5.0.0"

open FsHttp
open FsHttp.DslCE

let rec retry request resultOk retries =
    async {
        let! res = request |> Request.sendAsync

        if (resultOk res) || (retries = 0) then
            return res
        else
            return! retry request resultOk (retries - 1)
    }

async {
    let request =
        httpLazy { GET "http://httpbin.org/status/500:4,200:1" }

    let! result = retry request (fun r -> int r.statusCode = 200) 10
    printfn $"status code = {int result.statusCode}"
}
|> Async.RunSynchronously
```
</p>
</details>

**Comment by ronaldschlenker** [comment]
060ef0be914355b6b369a3fd3c1902f1c93ad96e

**Comment by ronaldschlenker** [comment]
Hi @naartjie ,

thank you a lot for your comment!

Basically, in my opinion there's nothing wrong with the way you use the library in your context (retry). Anyway, the need for additional async-wrapping seems inconvenient, and you are right:

> I soon realised that the `httpAsync { ... }` async builder fires off the request as soon as it's evaluated, i.e. it's a "hot" task like in C# land, rather than the cold async task idiomatic to F#

To solve this, I just released v5.1.0 on NuGet, which adds a `httpLazyAsync` builder (commits 060ef0be914355b6b369a3fd3c1902f1c93ad96e and ae2d4782dce922243bcd7a7d054a3f8c9b70e9e8).

I adjusted your example using Tomas' retry snippet a bit using that new builder. 

```fsharp
let rec retry work resultOk retries = async {
    let! res = work
    if (resultOk res) || (retries = 0) then return res
    else return! retry work resultOk (retries - 1) }
let work = 
    httpLazyAsync {
        GET "http://httpbin.org/status/500:10,200:1"
    }
let retryRes =
    retry work (fun r -> int r.statusCode = 200) 5
    |> Async.RunSynchronously
```

Again, thanks a lot, and I always appreciate feedback (especially since the lib is mostly driven by my personal needs).

**Comment by naartjie** [comment]
This is great, thanks a lot @ronaldschlenker!

I gave it a try, and it works very nicely.

**Comment by ronaldschlenker** [comment]
You’re welcome, thank you, too! Have a nice time and - as it’s said these times - stay healthy.
