### ISSUE TITLE
query params are being escaped but not url encoded which makes `query` useless

### ISSUE THREAD

**Issue by mabasic** [ronaldschlenker/FsHttp#67]
See these lines:
https://github.com/ronaldschlenker/FsHttp/blob/72f78fd476ddbc1559857be2ef1ef83bc28a7b00/src/FsHttp/Helper.fs#L30-L31

You are escaping the values, but not encoding them. Above there is a function called `urlEncode` which is not being used.

https://github.com/ronaldschlenker/FsHttp/blob/72f78fd476ddbc1559857be2ef1ef83bc28a7b00/src/FsHttp/Helper.fs#L9

I am trying with `fields[member]`. If passed as is, the API complains that I need to encode `[` and `]`, but when I do `HttpUtility.UrlEncode "fields[member]"` I get an error saying "Unknown parameter". If I add the query param in the `GET url` with `HttpUtility.UrlEncode "fields[member]` then it works.

I'll send a PR if that is ok with you.

**Comment by ronaldschlenker** [comment]
The HttpUtilities should be private, anyway. But I don't understand what exactly you do. Yould you please post a reproducable code example?

**Comment by mabasic** [comment]
I'll send it this evening.

I've been trying to fix this but then encountered issues with testing my fix.

So basically this is what happens:

An API to which I am sending a GET request wants that all query params are url encoded, meaning that chars like `[` and `]` need to be encoded.

I encode the param myself, but then when I pass it to the `query` function it gets escaped and ends up being wrong.

**Comment by ronaldschlenker** [comment]
Ok, I'll have a look again, but if you can provide an example later, that would be great.

**Comment by mabasic** [comment]
It seems that you have fixed the issue. Thank you.

**Comment by ronaldschlenker** [comment]
Since I already made some minor breaking changes and plan to make some more, will it be ok for you having a 6.0 prerelease?

**Comment by mabasic** [comment]
It is ok for me as long as I can reference it in my notebook (fsi).

If there is a way to reference the master branch I would be okay with that too, but can't find a way to do so.

**Comment by ronaldschlenker** [comment]
In F# interactive, it is possible with

```fsharp
#r "nuget: SchlenkR.FsHttp, 6.0.0-preview1"
```

I guess the same applied for notebooks.

I'll release it this evening.

**Comment by mabasic** [comment]
Awesome, thank you!

**Comment by ronaldschlenker** [comment]
https://www.nuget.org/packages/SchlenkR.FsHttp/6.0.0-preview1

**Comment by mabasic** [comment]
I am using `6.0.0-preview1` and it works now.

**Comment by ronaldschlenker** [comment]
Thanks for your support!
