### ISSUE TITLE
Issues with testing

### ISSUE THREAD

**Issue by mabasic** [ronaldschlenker/FsHttp#68]
When running `dotnet test src` I get mixed results every time I run the the tests:

```
Error Message:
   System.AggregateException : One or more errors occurred. (Connection refused (127.0.0.1:8080))
  ----> System.Net.Http.HttpRequestException : Connection refused (127.0.0.1:8080)
  ----> System.Net.Sockets.SocketException : Connection refused
  Stack Trace:
```

Every time a different test fails for this same reason. Don't know how to fix or debug this...

**Comment by mabasic** [comment]
I think that this happens because Suave server is started async and it takes time for it to start, but the test code runs before the server has started.

**Comment by ronaldschlenker** [comment]
Thanks @mabasic  for investigating. I just comitted a fix. Could you cross check if it works for you, since I can't reproduce the issue (because it's not deterministic).

**Comment by mabasic** [comment]
Great work! I will test this evening and report back.

I've been trying yesterday for a couple of hours to fix this, but my F# knowledge is lacking. I see that I was on the right track with watching the `listening` variable..

**Comment by mabasic** [comment]
Just tested and it works now. All tests pass no matter how many times I run them.
