### ISSUE TITLE
make domain interfaces like IToRequest public, so that we can extend the CE DSL on our own

### ISSUE THREAD

**Issue by DieselMeister** [ronaldschlenker/FsHttp#78]
Hi, it would be awesome, when you make domain interfaces like IToRequest public, so that we can extend the CE DSL on our own.

```fsharp

type LazyHttpBuilder<'context
                                when 'context :> FsHttp.Domain.IToRequest 
                                and 'context :> FsHttp.Domain.IToBodyContext 
                                and 'context :> FsHttp.Domain.IToMultipartContext> with

            [<CustomOperation("MyOwnStuff")>]
            member this.MyOwnStuff(builder: LazyHttpBuilder<_>, name, value) =
                ...

```

leads to an error, because the contraining interfaces (IToRequest, IToBodyContext, IToMultipartContext) are not accessable.

btw awesome project. Thank you!

**Comment by ronaldschlenker** [comment]
Hi @DieselMeister - thanks for the request.

[Here](https://github.com/ronaldschlenker/FsHttp/blob/master/src/Tests/ExtendingBuilders.fs) is an example of how to extend the builder with a custom operation.

This can be used with release 6.0.0-preview8.

**Comment by ronaldschlenker** [comment]
> btw awesome project. Thank you!

Thank you very much :) BTW, just starred https://github.com/DieselMeister/Terminal.Gui.Elmish :)

**Comment by DieselMeister** [comment]
I have it redesigned and started to build in a tree diff algo into the terminal.gui.elmish and will update it to the newer versions. But the time! (work took most of my time) ... So it's working with the older versions of terminal.gui

**Comment by DieselMeister** [comment]
> Hi @DieselMeister - thanks for the request.
> 
> [Here](https://github.com/ronaldschlenker/FsHttp/blob/master/src/Tests/ExtendingBuilders.fs) is an example of how to extend the builder with a custom operation.
> 
> This can be used with release [6.0.0-preview8](https://www.nuget.org/packages/SchlenkR.FsHttp/6.0.0-preview8)

Thank you! That was fast ...
